=== stumathews/stulibjava/JavaAndXML_Book_Src/Chapter15/Listing1503/Salesperson.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Salesperson.dtd -->

<!ELEMENT Salesperson (Total, Sale*)>
<!ATTLIST Salesperson fullName CDATA #REQUIRED>

<!ELEMENT Total (#PCDATA)>

<!ELEMENT Sale (ItemName, UnitCost, Quantity)>

<!ELEMENT ItemName (#PCDATA)>
<!ELEMENT UnitCost (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>

=== stumathews/stulibjava/JavaAndXML_Book_Src/Chapter15/Listing1501/Salesperson.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Salesperson SYSTEM "Salesperson.dtd">
<!-- Salesperson.xml -->

<Salesperson fullName="Barry Burd">
   <Total>1130.00</Total>
  
   <Sale>
      <ItemName>Widget</ItemName>
      <UnitCost>30.00</UnitCost>
      <Quantity>2</Quantity>
   </Sale>
  
   <Sale>
      <ItemName>Thingamabob</ItemName>
      <UnitCost>100.00</UnitCost>
      <Quantity>1</Quantity>
   </Sale>
  
   <Sale>
      <ItemName>Doohickey</ItemName>
      <UnitCost>23.00</UnitCost>
      <Quantity>5</Quantity>
   </Sale>  
</Salesperson>
