=== stumathews/stulibjava/JavaAndXML_Book_Src/Chapter06/Listing0607/Song.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Song.dtd -->

<!ENTITY Largo "4000">
<!ENTITY Andante "3000">
<!ENTITY Moderato "2000">
<!ENTITY Allegro "1000">

<!ELEMENT song (measure*)>
<!ATTLIST song tempo CDATA "&Moderato;">

<!ENTITY sixteenth "0.0625">
<!ENTITY eighth "0.125">
<!ENTITY quarter "0.25">
<!ENTITY half "0.5">
<!ENTITY whole "1.0">

<!ELEMENT measure (beat*)>
<!ATTLIST measure beatlength CDATA "&quarter;">

<!ELEMENT beat (note*)>

<!ELEMENT note EMPTY>
<!ATTLIST note
   pitch CDATA #REQUIRED
   octave CDATA "0"
   velocity CDATA #IMPLIED
   duration CDATA "&quarter;"
   dotted CDATA "false"
>

<!ENTITY A "57">
<!ENTITY Asharp "58">
<!ENTITY Bflat "58">
<!ENTITY B "59">
<!ENTITY C "60">
<!ENTITY Csharp "61">
<!ENTITY Dflat "61">
<!ENTITY D "62">
<!ENTITY Dsharp "63">
<!ENTITY Eflat "63">
<!ENTITY E "64">
<!ENTITY F "65">
<!ENTITY Fsharp "66">
<!ENTITY Fflat "66">
<!ENTITY G "67">
<!ENTITY Gsharp "68">
<!ENTITY Aflat "68">

<!ENTITY piano "45"> 
<!ENTITY forte "120">

=== stumathews/stulibjava/JavaAndXML_Book_Src/Chapter06/Listing0606/XMLBaby.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE song SYSTEM "song.dtd">

<song tempo="&Andante;">
   <measure beatlength="&eighth;">
      <beat/><beat/><beat/><beat/><beat/>      
      
      <beat><!-- My -->
         <note pitch="&Eflat;" duration="&eighth;"/>
      </beat>
      
      <beat><!-- screen's -->
         <note pitch="&Eflat;" duration="&eighth;"/>
      </beat>
      
      <beat><!-- a -->
         <note pitch="&C;" duration="&eighth;"/>
      </beat>
   </measure>
   
   <measure beatlength="&eighth;">      
      <beat><!-- free- -->
         <note pitch="&Eflat;" velocity="&forte;" 
                               duration="&eighth;"/>
         <note pitch="&C;" octave="-1" 
               velocity="&piano;" duration="&quarter;"/>
         <note pitch="&G;" octave="-1" 
               velocity="&piano;" duration="&quarter;"/>
      </beat>
      <beat><!-- zin' -->
         <note pitch="&Eflat;" duration="&eighth;"/>
      </beat>
      
      <beat><!-- up -->
         <note pitch="&Eflat;" duration="&eighth;"/>
         <note pitch="&A;" velocity="&piano;"/>
      </beat>
      <beat><!-- ba- -->
         <note pitch="&Eflat;" duration="&eighth;"/>
      </beat>
      
      <beat>
         <note pitch="&Bflat;" velocity="&piano;"/>
      </beat>
      <beat><!-- by -->
         <note pitch="&C;" duration="&half;"/>
      </beat>
      
      <beat>
         <note pitch="&A;" velocity="&piano;"/>         
      </beat>      
      <beat/>      
   </measure>
   
   <measure beatlength="&sixteenth;">
      <beat>
         <note pitch="&C;" octave="-1" velocity="&piano;"/>
         <note pitch="&G;" octave="-1" velocity="&piano;"/>
      </beat>
      <beat/>            
      <beat><!-- but -->
         <note pitch="&F;" duration="&sixteenth;"/>
      </beat>      
      <beat><!-- my -->
         <note pitch="&F;" duration="&sixteenth;"/>
      </beat>      
      
      <beat><!-- heart's -->
         <note pitch="&F;" velocity="&forte;"
                           duration="&eighth;"/>         
         <note pitch="&A;" velocity="&piano;"/>
      </beat>
      <beat/>      
      <beat><!-- X -->
         <note pitch="&G;" duration="&sixteenth;"/>
      </beat>
      <beat><!-- M -->
         <note pitch="&F;" duration="&sixteenth;"/>
      </beat>
      
      <beat><!-- L- -->
         <note pitch="&Eflat;" velocity="&forte;" 
                               duration="&eighth;"/>               
         <note pitch="&Bflat;" velocity="&piano;"/>
      </beat>
      <beat/>     
      <beat><!-- ting -->
         <note pitch="&C;" duration="&eighth;"/>
      </beat>
      <beat/>      
      
      <beat><!-- for -->
         <note pitch="&Bflat;" duration="&eighth;"/>
      </beat>  
      <beat/>          
      <beat><!-- you. -->
         <note pitch="&C;" duration="&half;"/>
      </beat>
      <beat/>      
   </measure>
      
</song>
